(function(){var httpRequest;var result=[];var thumbsContainer=document.getElementById("thumbsContainer");var featuredContainer=document.getElementById("featuredContainer");function addClass(el,elClass){if(el.className.indexOf(elClass)===-1)el.className+=" "+elClass}function removeClass(el,elClass){if(el.className.indexOf(elClass)>0){var re=new RegExp(elClass,"i");el.className=el.className.replace(re,"");el.className.trim()}}function ajaxLoader(obj,url){if(window.XMLHttpRequest)httpRequest=new XMLHttpRequest;
else if(window.ActiveXObject)try{httpRequest=new window.ActiveXObject("Msxml2.XMLHTTP")}catch(e){try{httpRequest=new window.ActiveXObject("Microsoft.XMLHTTP")}catch(ex){alert("N\u00e3o foi poss\u00edvel conectar:\n"+ex.toString())}}if(!httpRequest){alert("N\u00e3o foi poss\u00edvel criar instancia do objeto XMLHTTP");return false}httpRequest.onreadystatechange=function(){if(httpRequest.readyState===4)if(httpRequest.status===200){result=JSON.parse(httpRequest.responseText);if(result.stat==="fail"){alert(result.message);
return false}else if(result.stat==="ok")obj.createGallery(result)}else alert("Ocorreu um erro durante a requisi\u00e7\u00e3o.")};httpRequest.open("GET",url);httpRequest.send()}function Gallery(gallery_id){this.gallery_id=gallery_id;this.api_key="da9ca8df6dd3e9be07fa4364c5ae1134";this.per_page=12}Gallery.prototype.init=function(){var url="http://api.flickr.com/services/rest/?method=flickr.photosets.getPhotos&api_key="+this.api_key+"&photoset_id="+this.gallery_id+"&format=json&nojsoncallback=1";ajaxLoader(this,
url)};Gallery.prototype.createGallery=function(json){this.total=json.photoset.total;this.pages=json.photoset.pages;this.thumbs=document.createElement("ul");this.thumbs.className="thumbnails";var controller=document.createElement("div");controller.id="controller";var nextPhoto=document.createElement("div");nextPhoto.id="nextPhoto";nextPhoto.innerHTML='<a href="javascript:;"><span></span></a>';var previousPhoto=document.createElement("div");previousPhoto.id="previousPhoto";previousPhoto.innerHTML='<a href="javascript:;"><span></span></a>';
controller.appendChild(previousPhoto);controller.appendChild(nextPhoto);var featuredImgContainer=document.createElement("div");featuredImgContainer.className="featuredImgContainer";var holder=document.createElement("div");holder.id="holder";holder.appendChild(controller);featuredImgContainer.appendChild(holder);var h1=document.createElement("h1");this.featuredCount=document.createElement("p");this.featuredCount.className="counter";featuredContainer.appendChild(this.featuredCount);featuredContainer.appendChild(h1);
featuredContainer.appendChild(featuredImgContainer);var obj=this;nextPhoto.addEventListener("click",function(){obj.navNextPhoto()},false);previousPhoto.addEventListener("click",function(){obj.navPreviousPhoto()},false);this.photosArr=json.photoset.photo;var thumbFormat="q";var galleryObj=this;for(var i=0;i<this.photosArr.length;i++){var photo=this.photosArr[i];var li=document.createElement("li");li.className="span1";li.innerHTML='<a class="thumbnail" href="javascript:;" title="'+photo.title+'"><img src="http://farm'+
photo.farm+".staticflickr.com/"+photo.server+"/"+photo.id+"_"+photo.secret+"_"+thumbFormat+'.jpg" /></a>';li.rel=i;li.obj=galleryObj;li.onclick=galleryObj.thumbClick;this.thumbs.appendChild(li)}this.setFeatured(0);thumbsContainer.appendChild(this.thumbs);this.createPages()};Gallery.prototype.thumbClick=function(){this.obj.setFeatured(this.rel)};Gallery.prototype.setFeatured=function(index){this.photoActive=index;this.featuredCount.innerHTML='Foto <span class="badge">'+(index+1)+'</span> de <span class="badge">'+
this.total+"</span>";var thumbs=this.thumbs;for(var i=0;i<thumbs.childNodes.length;i++)removeClass(thumbs.childNodes[i].firstChild,"active");addClass(thumbs.childNodes[index].firstChild,"active");var photo=this.photosArr[index];var holder=document.getElementById("holder");var newImg=document.createElement("img");newImg.className="img-polaroid";var featuredFormat="z";newImg.src="http://farm"+photo.farm+".staticflickr.com/"+photo.server+"/"+photo.id+"_"+photo.secret+"_"+featuredFormat+".jpg";featuredContainer.getElementsByTagName("h1")[0].innerHTML=
photo.title?photo.title:"Sem t\u00edtulo";var actualImg=holder.getElementsByTagName("img")[0];if(actualImg)holder.removeChild(actualImg);holder.appendChild(newImg);this.navPhotos()};Gallery.prototype.navPhotos=function(){var previousPhoto=document.getElementById("previousPhoto");previousPhoto.firstChild.className="";var nextPhoto=document.getElementById("nextPhoto");nextPhoto.firstChild.className="";if(this.photoActive===0)previousPhoto.firstChild.className="disabled";if(this.photoActive==this.total-
1)nextPhoto.firstChild.className="disabled"};Gallery.prototype.navNextPhoto=function(){if(this.photoActive==this.total-1)return false;this.setFeatured(this.photoActive+1)};Gallery.prototype.navPreviousPhoto=function(){if(this.photoActive===0)return false;this.setFeatured(this.photoActive-1)};Gallery.prototype.createPages=function(){if(this.total<this.per_page)return;var pagesContainer=document.createElement("ul");pagesContainer.className="pages";var pages=this.total%this.per_page>0?Math.floor(this.total/
this.per_page)+1:this.total/this.per_page;var obj=this;for(var i=1;i<=pages;i++){var li=document.createElement("li");li.innerHTML='<a class="page" href="javascript:;" title="P\u00e1gina '+i+'">'+i+"</a>";li.obj=obj;li.onclick=obj.setPage;pagesContainer.appendChild(li)}thumbsContainer.appendChild(pagesContainer);this.goToPage(pagesContainer.firstChild)};Gallery.prototype.setPage=function(){for(var i=0;i<this.parentNode.childNodes.length;i++)this.parentNode.childNodes[i].className="";this.obj.goToPage(this)};
Gallery.prototype.goToPage=function(page){var pageIndex=page.firstChild.innerHTML;for(var i=0;i<this.total;i++){var el=this.thumbs.childNodes[i];removeClass(el,"show");if(i<pageIndex*this.per_page&&i>=pageIndex*this.per_page-this.per_page)addClass(el,"show")}page.className="active"};var form=document.getElementById("form");form.onsubmit=function(){var gallery_id=document.getElementById("gallery_id").value;if(gallery_id!==""){thumbsContainer.innerHTML="";featuredContainer.innerHTML="";var gallery=
new Gallery(gallery_id);gallery.init()}else alert("Insira o ID de um \u00e1lbum!");return false}})();